# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  webapibackend:
    image: webapibackend
    build:
      context: .
      dockerfile: WebApiBackend/Dockerfile
    ports:
      - 5285
  razorfrontend:
    image: razorfrontend
    build:
      context: .
      dockerfile: RazorFrontend/Dockerfile
    ports:
      - 5202:5202
