# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  webapibackend:
    image: webapibackend
    build:
      context: .
      dockerfile: WebApiBackend/Dockerfile
    ports:
      - 5285:5285
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
